In [1]:
import numpy as np

In [2]:
doc_vec = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])

In [3]:
doc_vec

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

cara inefisien, double loop

In [4]:
row, col = doc_vec.shape

In [7]:
dists = []
for i in range(row):
    doc_dist = []
    for j in range(row):
        sub = doc_vec[i, :] - doc_vec[j, :]
        squared = sub**2
        dist = squared.sum()**0.5
        doc_dist.append(dist)
    dists.append(doc_dist)

dists = np.array(dists)

In [8]:
dists

array([[0., 2., 4.],
       [2., 0., 2.],
       [4., 2., 0.]])

In [9]:
dists = []
for i in range(row):
    doc_dist = []
    for j in range(row):
        dist = np.linalg.norm(doc_vec[i, :] - doc_vec[j, :], ord=2)
        doc_dist.append(dist)
    dists.append(doc_dist)

dists = np.array(dists)

In [10]:
dists

array([[0., 2., 4.],
       [2., 0., 2.],
       [4., 2., 0.]])

cara lumayan, single loop

In [11]:
a = np.tile(doc_vec[0, :], (3,1))
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [12]:
a.sum(axis=1)

array([4, 4, 4])

In [13]:
a.sum(axis=0)

array([3, 3, 3, 3])

In [14]:
dists = []
for i in range(row):
    repeated_a = np.tile(doc_vec[i, :], (row, 1))
    sub = repeated_a - doc_vec
    squared = sub**2
    dist = squared.sum(axis=1)**0.5
    dists.append(dist)

dists = np.vstack(dists)

In [15]:
dists

array([[0., 2., 4.],
       [2., 0., 2.],
       [4., 2., 0.]])

In [16]:
dists = []
for i in range(row):
    repeated_a = np.tile(doc_vec[i, :], (row, 1))
    dist = np.linalg.norm(repeated_a - doc_vec, ord=2, axis=1)
    dists.append(dist)

dists = np.vstack(dists)

In [17]:
dists

array([[0., 2., 4.],
       [2., 0., 2.],
       [4., 2., 0.]])

In [18]:
dists = []
for i in range(row):
    dist = np.linalg.norm(doc_vec[i, :] - doc_vec, ord=2, axis=1)  # use broadcasting
    dists.append(dist)

dists = np.vstack(dists)

In [19]:
dists

array([[0., 2., 4.],
       [2., 0., 2.],
       [4., 2., 0.]])

cara efisien, tanpa loop

https://stackoverflow.com/questions/1550130/cloning-row-or-column-vectors

In [ ]:
np.tile(doc_vec.transpose(), (3,1)).reshape(3,4,3)

In [ ]:
left = np.tile(doc_vec.transpose(), (3,1)).reshape(3,4,3)
left[0, :, 0], left[1, :, 0], left[2, :, 0], left[0, :, 1], left[1, :, 1]

In [ ]:
right = np.tile(doc_vec, (1,3)).reshape(3,4,3)
right[0, :, 0], right[1, :, 0], right[2, :, 0], right[0, :, 1], right[1, :, 1]

In [ ]:
sub = left-right
squared = sub**2
summed = squared.sum(axis=1)
dists = summed**0.5

In [ ]:
dists

In [ ]:
dists = np.linalg.norm(left-right, ord=2, axis=1)

In [ ]:
dists

more eficient, use broadcast on the right side

In [ ]:
dists = np.linalg.norm(left-doc_vec[:, :, np.newaxis], ord=2, axis=1)

In [ ]:
dists