In [5]:
import multiprocessing as mp

import numpy as np

In [2]:
doc_vec = np.load('doc_vec.npy')

In [3]:
N, D = doc_vec.shape

In [4]:
def get_relevant_doc(i):
    dist = np.linalg.norm(doc_vec[i, :] - doc_vec, ord=2, axis=1)
    relevant = np.argsort(dist)[:6]
    return relevant

In [6]:
pool = mp.Pool(processes=14)
results = pool.map(get_relevant_doc, range(N))

In [7]:
results[:10]

[array([    0,  7552, 12788, 13195,  6956,  8483]),
 array([   1, 2893, 4375, 5240, 4168, 4321]),
 array([    2,  2400,  3919, 26140,  4553,  4720]),
 array([   3, 2253, 2373, 9366, 1457, 1144]),
 array([   4, 2186,  274,  275, 2778, 1769]),
 array([    5,  2853,  2864, 17640,  3597,  2721]),
 array([    6,    75,  3731,  4044,  7901, 20345]),
 array([   7, 1073, 5080, 3644, 4580, 4150]),
 array([    8,  9979, 17007, 17409, 21273, 20365]),
 array([    9, 18298, 13632,  1130, 10605,  6252])]

In [9]:
results = np.vstack(results)

In [13]:
np.save('top5.npy', results[:, 1:])